# Generated by Django 3.2 on 2021-04-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of pet', max_length=100)),
                ('breed', models.CharField(help_text='Breed a pet', max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', help_text='Sex of pet', max_length=15)),
                ('birth_date', models.DateField(help_text='Birth date of pet')),
                ('vaccinated', models.BooleanField(help_text='Whether or not pet is vaccinated')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture of pet', upload_to='profile_images')),
                ('bio', models.TextField(blank=True)),
                ('adopt_me_if', models.TextField(blank=True)),
                ('first_thing_people_notice_about_me', models.TextField(blank=True)),
                ('firday_night', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.EmailField(help_text='Email of adopter', max_length=254)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightings.pet')),
            ],
        ),
    ]
