# Generated by Django 3.1.7 on 2021-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='latitude')),
                ('longitude', models.FloatField(help_text='longitude')),
                ('squirrel_id', models.CharField(help_text='unique id of the squirrel', max_length=25)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='shift', max_length=5)),
                ('date', models.DateField(help_text='date')),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Baby', 'Baby'), ('Unknown', 'Unknown')], help_text='age of the squirrel', max_length=15)),
                ('primary_fur_color', models.CharField(choices=[('Grey', 'Grey'), ('Blond', 'Blond'), ('Black', 'Black'), ('White', 'White')], help_text='primary fur color', max_length=15)),
                ('location', models.CharField(choices=[('above tree', 'above tree'), ('above ground', 'above ground'), ('Unknown', 'unknown')], default='Unknown', help_text='location', max_length=25)),
                ('specific_location', models.CharField(blank=True, help_text='specific location', max_length=50)),
                ('running', models.BooleanField(default=False, help_text='running')),
                ('chasing', models.BooleanField(default=False, help_text='chasing')),
                ('climbing', models.BooleanField(default=False, help_text='climbing')),
                ('eating', models.BooleanField(default=False, help_text='eating')),
                ('foraging', models.BooleanField(default=False, help_text='foraging')),
                ('other_activities', models.CharField(blank=True, help_text='other activities', max_length=50)),
                ('kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('moans', models.BooleanField(default=False, help_text='Moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Tail Flags')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Tail Twitches')),
                ('approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('runs_from', models.BooleanField(default=False, help_text='Runs From')),
            ],
        ),
    ]
