# Generated by Django 3.1.7 on 2021-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown')], help_text='age of the squirrel', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('Unknown', 'unknown')], default='Unknown', help_text='location', max_length=25),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('Grey', 'Grey'), ('Black', 'Black'), ('Clinamon', 'Clinamon')], help_text='primary fur color', max_length=15),
        ),
    ]
