# Generated by Django 3.2 on 2021-04-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20210409_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='X',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Y',
            new_name='Longitude',
        ),
    ]
