# Generated by Django 3.1.7 on 2021-04-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20210409_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='squirrel_id',
            new_name='unique_squirrel_id',
        ),
    ]
