# Generated by Django 3.2 on 2021-04-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20210410_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(help_text='Latitude of the location', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(help_text='Longitude of the location', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Is the sighting in the morning or in the afternoon?', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Squirrel_ID',
            field=models.CharField(default=None, help_text='Unique Squirrel ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
