# Generated by Django 3.2 on 2021-04-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20210410_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(blank=True, help_text='Click the button to select the date'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='Location', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Please sepecify other activities you saw', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamom', 'Cinnamom'), ('Black', 'Black')], default=999, help_text='Primary Fur Color', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=20, null=True),
        ),
    ]
