# Generated by Django 3.2 on 2021-04-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20210410_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamom', 'Cinnamom'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=100, null=True),
        ),
    ]
